name : My First Workflow

on: push

jobs:
    firs_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "My first Github actions"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md
              