name: Serial Cowsay Workflow with Artifacts

on: push

jobs:
  install_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt
        run: sudo apt-get update

      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: Run cowsay and write to file
        run: cowsay "Hello from Job 1 🐄" > cowsay.txt

      - name: Upload cowsay.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: cowsay-file
          path: cowsay.txt

  write_file:
    needs: install_and_run
    runs-on: ubuntu-latest
    steps:
      - name: Download cowsay.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: cowsay-file

      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: Append new message
        run: cowsay "More fun in Job 2 🐮" >> cowsay.txt

      - name: Upload updated file
        uses: actions/upload-artifact@v4
        with:
          name: cowsay-file-updated
          path: cowsay.txt

  check_file:
    needs: write_file
    runs-on: ubuntu-latest
    steps:
      - name: Download updated cowsay.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: cowsay-file-updated

      - name: Check if file exists and print content
        run: |
          if [ -f cowsay.txt ]; then
            echo "✅ File exists. Content:"
            cat cowsay.txt
          else
            echo "❌ cowsay.txt not found!"
            exit 1
          fi
