name: Cowsay Workflow with Artifacts

on: push

jobs:
  job1_install_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay
        run: |
          sudo apt-get update
          sudo apt-get install cowsay -y

      - name: Copy cowsay binary
        run: |
          cp $(which cowsay) ./cowsay

      - name: Upload cowsay binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cowsay-binary
          path: cowsay

  job2_run_and_save_output:
    runs-on: ubuntu-latest
    needs: job1_install_and_upload
    steps:
      - name: Download cowsay binary
        uses: actions/download-artifact@v4
        with:
          name: cowsay-binary

      - name: Make binary executable
        run: chmod +x cowsay

      - name: Run cowsay and save output
        run: |
          ./cowsay "Hello from Job 2 🐮" > cowsay_output.txt
          sleep 10

      - name: Upload cowsay output
        uses: actions/upload-artifact@v4
        with:
          name: cowsay-output
          path: cowsay_output.txt

  job3_check_and_deploy:
    runs-on: ubuntu-latest
    needs: job2_run_and_save_output
    steps:
      - name: Download cowsay output
        uses: actions/download-artifact@v4
        with:
          name: cowsay-output

      - name: Check if file exists and deploy
        run: |
          if [ -f cowsay_output.txt ]; then
            echo "✅ Deploying..."
            cat cowsay_output.txt
          else
            echo "❌ cowsay_output.txt not found"
            exit 1
