name: Parallel Cowsay Failure Test

on: push

jobs:
  install_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt
        run: sudo apt-get update

      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: Run cowsay and write to file
        run: cowsay "Hello from Job 1 🐄" > cowsay.txt

      - name: Show file content
        run: cat cowsay.txt

  write_file:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 10 seconds
        run: sleep 10

      - name: Try to run cowsay (without installing it)
        run: cowsay "This will fail because cowsay is not installed" > cowsay.txt

      - name: Show file
        run: cat cowsay.txt

  check_file:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 10 seconds
        run: sleep 10

      - name: Check if file exists
        run: |
          if [ -f cowsay.txt ]; then
            echo "✅ File exists!"
            cat cowsay.txt
          else
            echo "❌ File does NOT exist!"
            exit 1
          fi
