name: My SECOND Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Shell Script Run
        run: ./ascii-2nd.yml
     